### ISSUE TITLE
Support for Polymer 1.0

### ISSUE THREAD

**Issue by michaelonubogu** [bendavis78/paper-time-picker#2]
Hello, Any chance you have a version in the works for Polymer 1.0?

**Comment by bendavis78** [comment]
I'm currently working on updating `paper-date-picker` to 1.0 (see bendavis78/paper-date-picker#6). After that's done I'll be starting work on porting `paper-time-picker`. Also, the material spec has changed for pickers, so be on the lookout for that as well :-)

**Comment by jlayes** [comment]
I'm taking a stab at this and a lot of changes are needed. Different attribute binding syntax, no expressions in bindings, etc. Probably the biggest change is that Polymer 1.0 doesn't support templates inside SVG. Namespaces are handled differently in 1.0 than 0.5 and I'm not sure if/when this will be fixed. Right now, it looks like the best solution is to place numbers on the clock programmatically rather than repeat templates. I'll provide an update in a day or two.

**Comment by bendavis78** [comment]
Released 1.0.0

**Comment by jlayes** [comment]
Thanks Ben - your bit of DOM trickery on the SVG templates was a whole lot cleaner than the rabbit hole I went down. Sorry I wasn't more help!

**Comment by bendavis78** [comment]
@jayes, no problem. Sorry you had to go down a rabbit hole, I know that feeling :)
