### ISSUE TITLE
Can't move hour selector

### ISSUE THREAD

**Issue by SebastianBoyd** [bendavis78/paper-time-picker#22]
The hour selector won't move when I drag it however the minute selector works fine.

**Comment by SebastianBoyd** [comment]
Only happens when clock is not visible in initial load and needs to be scrolled to.

**Comment by RobinLinus** [comment]
Same here on iOS

**Comment by ThreeScreenStudios** [comment]
@bendavis78 - I think I found where the issue is. In paper-clock-selector.html, in the _onTouch method, the bounds checking is failing when it comes to the hour clock. Because the clocks are stacked, the hour clock has a much different top value than the minute clock. I tried fooling around with adjusting the y calculation but couldn't get it to work properly - hopefully this can help track down the problem?

**Comment by admwx7** [comment]
A fix is out for this, if someone is still experiencing the issue, create a new PR and tag me in it please!
